### Создание пользователя
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "first_name": "Иван",
    "last_name": "Иванов",
    "age": 25
}

### Получение всех пользователей
GET http://localhost:3001/api/users

### Получение пользователя по ID
GET http://localhost:3001/api/users/69e9fbaddaf2140725317419

### Обновление пользователя
PATCH http://localhost:3001/api/users/69e9fbaddaf2140725317419
Content-Type: application/json

{
    "age": 199
}

### Удаление пользователя
DELETE http://localhost:3001/api/users/69e9fbaddaf2140725317419